# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-30 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_posts_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='date',
            new_name='data',
        ),
    ]
