# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-30 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20160630_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='data',
        ),
    ]
