# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-29 14:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_posts_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='content',
            new_name='tipo',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='title',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='updated',
        ),
        migrations.AddField(
            model_name='posts',
            name='contrato',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='detalhe',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='legenda',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='valor',
            field=models.FloatField(default=datetime.datetime(2016, 8, 29, 14, 11, 46, 299000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='posts',
            table='financeiros',
        ),
    ]
