# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-30 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_posts_nota'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={},
        ),
        migrations.AlterModelTable(
            name='posts',
            table=None,
        ),
    ]
