# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 18:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_auto_20160830_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='anexo',
            field=models.FileField(default=datetime.datetime(2016, 9, 6, 18, 35, 52, 903062, tzinfo=utc), upload_to=b''),
            preserve_default=False,
        ),
    ]
