# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_auto_20160906_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='anexo',
        ),
    ]
