# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0032_legendas'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos',
            name='obs',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
