# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FortalPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_chamado', models.BigIntegerField(blank=True, null=True)),
                ('local', models.CharField(blank=True, max_length=45, null=True)),
                ('detalhe', models.CharField(blank=True, max_length=45, null=True)),
                ('material', models.CharField(blank=True, max_length=45, null=True)),
                ('tecnico', models.CharField(blank=True, max_length=45, null=True)),
                ('profissional', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, max_length=17, null=True)),
                ('data', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inss_fortal_chamados',
            },
        ),
    ]
