# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortalposts', '0002_fortalposts_anexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FortalProfissionals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=45, null=True)),
                ('cpf', models.CharField(blank=True, max_length=45, null=True)),
                ('cargo', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'inss_fortal_profissionals',
            },
        ),
        migrations.AlterField(
            model_name='fortalposts',
            name='anexo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fortalposts',
            name='detalhe',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='fortalposts',
            name='material',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
