# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortalposts', '0003_auto_20161031_0256'),
    ]

    operations = [
        migrations.CreateModel(
            name='FortalCidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'inss_fortal_cidades',
            },
        ),
        migrations.AlterField(
            model_name='fortalposts',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d'),
        ),
    ]
