# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-28 02:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.CharField(default=datetime.datetime(2016, 6, 28, 2, 14, 9, 724000, tzinfo=utc), max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(default=datetime.datetime(2016, 6, 28, 2, 14, 17, 873000, tzinfo=utc), max_length=45),
            preserve_default=False,
        ),
    ]
