# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-29 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20160829_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='nota',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
