# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-29 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_posts_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='nota',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
