# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-29 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20160829_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'managed': True},
        ),
    ]
