# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-30 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_delete_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato', models.CharField(blank=True, max_length=45, null=True)),
                ('legenda', models.CharField(blank=True, max_length=100, null=True)),
                ('detalhe', models.CharField(blank=True, max_length=500, null=True)),
                ('valor', models.FloatField()),
                ('data', models.DateField()),
                ('tipo', models.CharField(max_length=45)),
                ('nota', models.FileField(blank=True, max_length=45, null=True, upload_to=b'')),
            ],
        ),
    ]
