# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-30 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20160630_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
