# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-30 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20160829_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='nota',
        ),
    ]
