# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-30 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20160830_0947'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
