# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_auto_20160906_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='anexo',
            field=models.FileField(default=django.utils.timezone.now, upload_to=b''),
            preserve_default=False,
        ),
    ]
