# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-07 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0028_posts_anexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='anexo',
            field=models.FileField(upload_to='documents/%Y/%m/%d'),
        ),
    ]
